// <auto-generated />
using System;
using CDNSBlazorApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CDNSBlazorApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251124080927_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CDNSBlazorApp.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CDNSBlazorApp.Models.Instituation", b =>
                {
                    b.Property<string>("InstituationId")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("INSTITUATION_ID");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CONTACT_EMAIL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("CreatedAtValueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT_VALUE_DATE");

                    b.Property<string>("InstituationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("INSTITUATION_NAME");

                    b.HasKey("InstituationId");

                    b.ToTable("INSTITUATION");
                });

            modelBuilder.Entity("CDNSBlazorApp.Models.Instrument", b =>
                {
                    b.Property<string>("InstrumentId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("INSTRUMENT_ID");

                    b.Property<decimal>("Amt")
                        .HasPrecision(21, 3)
                        .HasColumnType("decimal(21,3)")
                        .HasColumnName("AMT");

                    b.Property<decimal>("AmtDiscounted")
                        .HasPrecision(21, 3)
                        .HasColumnType("decimal(21,3)")
                        .HasColumnName("AMT_DISCOUNTED");

                    b.Property<decimal>("AmtNet")
                        .HasPrecision(21, 3)
                        .HasColumnType("decimal(21,3)")
                        .HasColumnName("AMT_NET");

                    b.Property<string>("CdDebtSecIntrType")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CD_DEBT_SEC_INTR_TYPE");

                    b.Property<string>("CdDebtSource")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CD_DEBT_SOURCE");

                    b.Property<string>("CdDebtType")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CD_DEBT_TYPE");

                    b.Property<string>("CdDurCat")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CD_DUR_CAT");

                    b.Property<string>("CdEconSect")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CD_ECON_SECT");

                    b.Property<string>("CdInstrumentType")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CD_INSTRUMENT_TYPE");

                    b.Property<string>("CdLoPrp")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CD_LO_PRP");

                    b.Property<string>("CdLoStatus")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CD_LO_STATUS");

                    b.Property<string>("CdReorgGrp")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CD_REORG_GRP");

                    b.Property<string>("CdSourceModule")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CD_SOURCE_MODULE");

                    b.Property<string>("CdUserCode1")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CD_USER_CODE_1");

                    b.Property<int?>("CreditorId")
                        .HasColumnType("int")
                        .HasColumnName("CREDITOR_ID");

                    b.Property<string>("CuBase")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("CU_BASE");

                    b.Property<DateTime?>("DFinalMaturity")
                        .HasColumnType("datetime2")
                        .HasColumnName("D_FINAL_MATURITY");

                    b.Property<DateTime?>("DSign")
                        .HasColumnType("datetime2")
                        .HasColumnName("D_SIGN");

                    b.Property<int?>("DebtorId")
                        .HasColumnType("int")
                        .HasColumnName("DEBTOR_ID");

                    b.Property<string>("InstituationId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("INSTITUATION_ID");

                    b.Property<string>("IsinCode")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ISIN_CODE");

                    b.Property<string>("LongName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("LONG_NAME");

                    b.Property<string>("MaturityPeriod")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("MATURITY_PERIOD");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("NAME");

                    b.Property<string>("OriginalInstId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ORIGINAL_INST_ID");

                    b.HasKey("InstrumentId");

                    b.HasIndex("InstituationId");

                    b.ToTable("Instrument");
                });

            modelBuilder.Entity("CDNSBlazorApp.Models.Payment", b =>
                {
                    b.Property<string>("PaymentId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(0);

                    b.Property<int>("PaymentTraNo")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<decimal>("Amount")
                        .HasPrecision(21, 3)
                        .HasColumnType("decimal(21,3)")
                        .HasColumnName("AMOUNT");

                    b.Property<string>("CdAmountDiff")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CD_AMOUNT_DIFF");

                    b.Property<string>("CdPaymentMode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CD_PAYMENT_MODE");

                    b.Property<string>("CdTransactionType")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CD_TRANSACTION_TYPE");

                    b.Property<string>("CuBase")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("CU_BASE");

                    b.Property<DateTime?>("LocalExchRateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("LOCAL_EXCH_RATE_DATE");

                    b.Property<DateTime>("MadeDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MADE_DATE");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("RECEIVED_DATE");

                    b.Property<DateTime>("SchPaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("SCH_PAYMENT_DATE");

                    b.HasKey("PaymentId", "PaymentTraNo");

                    b.ToTable("PAYMENTS");
                });

            modelBuilder.Entity("CDNSBlazorApp.Models.Series", b =>
                {
                    b.Property<string>("SerieId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(0);

                    b.Property<int>("SerieTraNo")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("CdReorgGrp")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CD_REORG_GRP");

                    b.Property<decimal>("SerieAmt")
                        .HasPrecision(21, 3)
                        .HasColumnType("decimal(21,3)")
                        .HasColumnName("SERIE_AMT");

                    b.Property<string>("SerieCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("SERIE_CURRENCY");

                    b.HasKey("SerieId", "SerieTraNo");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("CDNSBlazorApp.Models.SeriesPattern", b =>
                {
                    b.Property<string>("SeriePatId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(0);

                    b.Property<int>("SeriePatTraNo")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<decimal?>("Amt")
                        .HasPrecision(21, 3)
                        .HasColumnType("decimal(21,3)")
                        .HasColumnName("AMT");

                    b.Property<string>("CdPatType")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CD_PAT_TYPE");

                    b.Property<string>("CdPeriodicity")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CD_PERIODICITY");

                    b.Property<string>("CgPeriodicity")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CG_PERIODICITY");

                    b.Property<DateTime?>("DFirstPayment")
                        .HasColumnType("datetime2")
                        .HasColumnName("D_FIRST_PAYMENT");

                    b.Property<DateTime?>("DLastPayment")
                        .HasColumnType("datetime2")
                        .HasColumnName("D_LAST_PAYMENT");

                    b.Property<int>("Percentage")
                        .HasColumnType("int")
                        .HasColumnName("PERCENTAGE");

                    b.HasKey("SeriePatId", "SeriePatTraNo");

                    b.ToTable("SERIES_PATTERN");
                });

            modelBuilder.Entity("CDNSBlazorApp.Models.Subscription", b =>
                {
                    b.Property<string>("SubscriptionId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(0);

                    b.Property<int>("SubscriptionIdTraNo")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("CdExecMode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CD_EXEC_MODE");

                    b.Property<string>("CdTransactionType")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CD_TRANSACTION_TYPE");

                    b.Property<string>("CuBase")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("CU_BASE");

                    b.Property<DateTime?>("LocalExchangeDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("LOCAL_EXCHANGE_DATE");

                    b.Property<decimal>("ReceiptsAmount")
                        .HasPrecision(21, 3)
                        .HasColumnType("decimal(21,3)")
                        .HasColumnName("RECEIPTS_AMOUNT");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("RECEIVED_DATE");

                    b.Property<DateTime>("TrDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("TR_DATE");

                    b.HasKey("SubscriptionId", "SubscriptionIdTraNo");

                    b.ToTable("SUBSCRIPTIONS");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CDNSBlazorApp.Models.Instrument", b =>
                {
                    b.HasOne("CDNSBlazorApp.Models.Instituation", "Instituation")
                        .WithMany("Instruments")
                        .HasForeignKey("InstituationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instituation");
                });

            modelBuilder.Entity("CDNSBlazorApp.Models.Payment", b =>
                {
                    b.HasOne("CDNSBlazorApp.Models.Instrument", "Instrument")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("CDNSBlazorApp.Models.Series", b =>
                {
                    b.HasOne("CDNSBlazorApp.Models.Instrument", "Instrument")
                        .WithMany("Series")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("CDNSBlazorApp.Models.SeriesPattern", b =>
                {
                    b.HasOne("CDNSBlazorApp.Models.Instrument", "Instrument")
                        .WithMany("SeriesPatterns")
                        .HasForeignKey("SeriePatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("CDNSBlazorApp.Models.Subscription", b =>
                {
                    b.HasOne("CDNSBlazorApp.Models.Instrument", "Instrument")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CDNSBlazorApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CDNSBlazorApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CDNSBlazorApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CDNSBlazorApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CDNSBlazorApp.Models.Instituation", b =>
                {
                    b.Navigation("Instruments");
                });

            modelBuilder.Entity("CDNSBlazorApp.Models.Instrument", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Series");

                    b.Navigation("SeriesPatterns");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
